#!/usr/bin/env bash
set -euo pipefail

# One command for collecting three server addresses, forming the Swarm, and
# optionally deploying the control plane or selected SwarmOps stacks.
# Passwords are deliberately handled by Ansible prompts, never this script.

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
inventory="$repo_root/deploy/ansible/inventory.yml"
hosts_dir="$repo_root/deploy/hosts"

apply=0
overwrite=0
password_auth=0
ask_become_pass=0
become_password_choice_set=0
install_password_helper=0
deploy_platform=0

ssh_user=""
manager_01=""
manager_02=""
manager_03=""
advertise_01=""
advertise_02=""
advertise_03=""
traefik_email=""
swarmops_host=""
traefik_dashboard_host=""
traefik_token_file=""
traefik_dashboard_auth_file=""
swarmops_admin_password_hash_file=""
swarmops_session_key_file=""
swarmops_agent_token_file=""
swarmops_registry_config_file=""
tag="$(git -C "$repo_root" rev-parse --short HEAD)"
releases=()
temporary_files=()
current_temp=""

usage() {
  printf '%s\n' \
    'Usage: bash scripts/setup-three-managers.sh [options]' \
    '' \
    'Required server inputs:' \
    '  --manager-01 <SSH-IP>       Edge/control manager.' \
    '  --manager-02 <SSH-IP>       Second manager.' \
    '  --manager-03 <SSH-IP>       Third manager.' \
    '  --ssh-user <user>           Existing SSH user; it must be able to sudo.' \
    '' \
    'Optional connection inputs:' \
    '  --advertise-01 <private-IP> Swarm address for manager-01.' \
    '  --advertise-02 <private-IP> Swarm address for manager-02.' \
    '  --advertise-03 <private-IP> Swarm address for manager-03.' \
    '  --password-auth             Prompt Ansible for the SSH password.' \
    '  --sudo-password             Also prompt for the sudo password.' \
    '  --no-sudo-password          Do not prompt for the sudo password.' \
    '  --install-password-helper   Install sshpass with Homebrew if needed.' \
    '' \
    'Execution:' \
    '  --apply                     Write ignored local config and change servers.' \
    '  --overwrite                 Replace existing ignored local config files.' \
    '' \
    'Optional platform/release phases (require --apply):' \
    '  --platform                  Deploy Traefik and SwarmOps after host bootstrap.' \
    '  --traefik-email <email>     ACME email for Traefik.' \
    '  --swarmops-host <hostname>  SwarmOps HTTPS hostname.' \
    '  --traefik-dashboard-host <hostname> Protected Traefik dashboard hostname.' \
    '  --traefik-token-file <path> Cloudflare token file outside the repository.' \
    '  --traefik-dashboard-auth-file <path> htpasswd dashboard-auth file outside the repository.' \
    '  --swarmops-admin-password-hash-file <path> bcrypt hash file outside the repository.' \
    '  --swarmops-session-key-file <path> random 32+ byte session key file outside the repository.' \
    '  --swarmops-agent-token-file <path> random agent token file outside the repository.' \
    '  --swarmops-registry-config-file <path> Docker registry config JSON outside the repository.' \
    '  --release <stack>           Build when needed and deploy one SwarmOps stack.' \
    '  --tag <git-sha>             Immutable image tag; defaults to current SHA.'
}

fail() {
  printf 'setup failed: %s\n' "$*" >&2
  exit 1
}

cleanup() {
  local file
  if (( ${#temporary_files[@]} )); then
    for file in "${temporary_files[@]}"; do
      [[ -n "$file" && -e "$file" ]] && rm -f -- "$file"
    done
  fi
}
trap cleanup EXIT

need_value() {
  (($# >= 2)) || fail "$1 requires a value"
}

safe_user() {
  [[ "$1" =~ ^[a-z_][a-z0-9_-]*[$]?$ ]]
}

safe_address() {
  [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9.:-]*$ ]]
}

safe_hostname() {
  [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9.-]*$ ]]
}

safe_email() {
  [[ "$1" =~ ^[^[:space:]@]+@[^[:space:]@]+$ ]]
}

safe_tag() {
  [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]]
}

prepare_target() {
  local target="$1"
  local directory
  directory="$(dirname "$target")"
  [[ ! -e "$target" || "$overwrite" == 1 ]] || {
    fail "refusing to replace $target; review it and use --overwrite"
  }
  mkdir -p "$directory"
}

create_temp_for() {
  local target="$1"
  local directory
  directory="$(dirname "$target")"
  current_temp="$(mktemp "$directory/.setup-three-managers.XXXXXX")"
  chmod 600 "$current_temp"
  temporary_files+=("$current_temp")
}

write_inventory() {
  prepare_target "$inventory"
  create_temp_for "$inventory"
  {
    printf '%s\n' '---'
    printf '%s\n' '# Generated by scripts/setup-three-managers.sh. This file is ignored by Git.'
    printf '%s\n' 'all:'
    printf '%s\n' '  vars:'
    printf '    ansible_user: %s\n' "$ssh_user"
    printf '%s\n' '    ansible_become: true'
    printf '%s\n' '    docker_users:'
    printf '      - "%s"\n' "$ssh_user"
    printf '%s\n' '    swarm_primary_manager: manager-01'
    printf '%s\n' '    swarm_overlay_network: traefik'
    printf '%s\n' '  children:'
    printf '%s\n' '    swarm_managers:'
    printf '%s\n' '      hosts:'
    printf '%s\n' '        manager-01:'
    printf '          ansible_host: %s\n' "$manager_01"
    printf '          swarm_advertise_addr: %s\n' "$advertise_01"
    printf '%s\n' '          swarm_node_labels:'
    printf '%s\n' '            swarmops.edge: "true"'
    printf '%s\n' '            swarmops.control: "true"'
    printf '%s\n' '            swarmops.stateful: "true"'
    printf '%s\n' '        manager-02:'
    printf '          ansible_host: %s\n' "$manager_02"
    printf '          swarm_advertise_addr: %s\n' "$advertise_02"
    printf '%s\n' '          swarm_node_labels: {}'
    printf '%s\n' '        manager-03:'
    printf '          ansible_host: %s\n' "$manager_03"
    printf '          swarm_advertise_addr: %s\n' "$advertise_03"
    printf '%s\n' '          swarm_node_labels: {}'
  } >"$current_temp"
  mv "$current_temp" "$inventory"
}

write_host_file() {
  local name="$1"
  local address="$2"
  local destination="$hosts_dir/$name.env"

  prepare_target "$destination"
  create_temp_for "$destination"
  {
    printf '%s\n' '# Generated by scripts/setup-three-managers.sh. This file is ignored by Git.'
    printf 'SSH_TARGET=%s@%s\n' "$ssh_user" "$address"
    printf 'DOCKER_CONTEXT=nim-%s\n' "$name"
    if [[ "$name" == manager-01 && -n "$traefik_email" ]]; then
      printf 'TRAEFIK_ACME_EMAIL=%s\n' "$traefik_email"
      printf 'SWARMOPS_HOST=%s\n' "$swarmops_host"
      printf 'TRAEFIK_DASHBOARD_HOST=%s\n' "$traefik_dashboard_host"
      printf 'TRAEFIK_DASHBOARD_URL=https://%s/dashboard/\n' "$traefik_dashboard_host"
      printf '%s\n' 'SWARMOPS_MUTATIONS_ENABLED=false'
      printf '%s\n' 'SWARMOPS_BUILD_ENABLED=false'
    fi
  } >"$current_temp"
  mv "$current_temp" "$destination"
}

validate_release() {
  case "$1" in
    traefik|swarmops|swarmops-observability|swarmops-logs)
      ;;
    *)
      fail "release must be one of: traefik, swarmops, swarmops-observability, swarmops-logs"
      ;;
  esac
}

while (($#)); do
  case "$1" in
    --manager-01)
      need_value "$@"
      manager_01="$2"
      shift 2
      ;;
    --manager-02)
      need_value "$@"
      manager_02="$2"
      shift 2
      ;;
    --manager-03)
      need_value "$@"
      manager_03="$2"
      shift 2
      ;;
    --advertise-01)
      need_value "$@"
      advertise_01="$2"
      shift 2
      ;;
    --advertise-02)
      need_value "$@"
      advertise_02="$2"
      shift 2
      ;;
    --advertise-03)
      need_value "$@"
      advertise_03="$2"
      shift 2
      ;;
    --ssh-user)
      need_value "$@"
      ssh_user="$2"
      shift 2
      ;;
    --password-auth)
      password_auth=1
      shift
      ;;
    --sudo-password)
      ask_become_pass=1
      become_password_choice_set=1
      shift
      ;;
    --no-sudo-password)
      ask_become_pass=0
      become_password_choice_set=1
      shift
      ;;
    --install-password-helper)
      install_password_helper=1
      shift
      ;;
    --apply)
      apply=1
      shift
      ;;
    --overwrite)
      overwrite=1
      shift
      ;;
    --platform)
      deploy_platform=1
      shift
      ;;
    --traefik-email)
      need_value "$@"
      traefik_email="$2"
      shift 2
      ;;
    --swarmops-host)
      need_value "$@"
      swarmops_host="$2"
      shift 2
      ;;
    --traefik-dashboard-host)
      need_value "$@"
      traefik_dashboard_host="$2"
      shift 2
      ;;
    --traefik-token-file)
      need_value "$@"
      traefik_token_file="$2"
      shift 2
      ;;
    --traefik-dashboard-auth-file)
      need_value "$@"
      traefik_dashboard_auth_file="$2"
      shift 2
      ;;
    --swarmops-admin-password-hash-file)
      need_value "$@"
      swarmops_admin_password_hash_file="$2"
      shift 2
      ;;
    --swarmops-session-key-file)
      need_value "$@"
      swarmops_session_key_file="$2"
      shift 2
      ;;
    --swarmops-agent-token-file)
      need_value "$@"
      swarmops_agent_token_file="$2"
      shift 2
      ;;
    --swarmops-registry-config-file)
      need_value "$@"
      swarmops_registry_config_file="$2"
      shift 2
      ;;
    --release)
      need_value "$@"
      releases+=("$2")
      shift 2
      ;;
    --tag)
      need_value "$@"
      tag="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "unknown argument: $1"
      ;;
  esac
done

[[ -n "$ssh_user" ]] || fail '--ssh-user is required'
[[ -n "$manager_01" ]] || fail '--manager-01 is required'
[[ -n "$manager_02" ]] || fail '--manager-02 is required'
[[ -n "$manager_03" ]] || fail '--manager-03 is required'
advertise_01="${advertise_01:-$manager_01}"
advertise_02="${advertise_02:-$manager_02}"
advertise_03="${advertise_03:-$manager_03}"

safe_user "$ssh_user" || fail 'SSH user must be a conventional Linux username'
for address in "$manager_01" "$manager_02" "$manager_03" "$advertise_01" "$advertise_02" "$advertise_03"; do
  safe_address "$address" || fail "invalid server address: $address"
done
safe_tag "$tag" || fail "invalid image tag: $tag"

if ((password_auth)) && [[ "$ssh_user" != root && "$become_password_choice_set" == 0 ]]; then
  ask_become_pass=1
fi

if ((deploy_platform)) || (( ${#releases[@]} )); then
  ((apply)) || fail '--platform and --release require --apply'
fi

if ((deploy_platform)); then
  [[ -n "$traefik_email" ]] || fail '--platform requires --traefik-email'
  [[ -n "$swarmops_host" ]] || fail '--platform requires --swarmops-host'
  [[ -n "$traefik_dashboard_host" ]] || fail '--platform requires --traefik-dashboard-host'
  [[ -n "$traefik_token_file" ]] || fail '--platform requires --traefik-token-file'
  [[ -n "$traefik_dashboard_auth_file" ]] || fail '--platform requires --traefik-dashboard-auth-file'
  [[ -n "$swarmops_admin_password_hash_file" ]] || fail '--platform requires --swarmops-admin-password-hash-file'
  [[ -n "$swarmops_session_key_file" ]] || fail '--platform requires --swarmops-session-key-file'
  [[ -n "$swarmops_agent_token_file" ]] || fail '--platform requires --swarmops-agent-token-file'
  [[ -n "$swarmops_registry_config_file" ]] || fail '--platform requires --swarmops-registry-config-file'
  safe_email "$traefik_email" || fail 'invalid Traefik email'
  safe_hostname "$swarmops_host" || fail 'invalid SwarmOps hostname'
  safe_hostname "$traefik_dashboard_host" || fail 'invalid Traefik dashboard hostname'
  [[ -s "$traefik_token_file" ]] || fail 'Cloudflare token file must exist and be non-empty'
  [[ -s "$traefik_dashboard_auth_file" ]] || fail 'Traefik dashboard-auth file must exist and be non-empty'
  [[ -s "$swarmops_admin_password_hash_file" ]] || fail 'SwarmOps bcrypt password-hash file must exist and be non-empty'
  [[ -s "$swarmops_session_key_file" ]] || fail 'SwarmOps session-key file must exist and be non-empty'
  [[ -s "$swarmops_agent_token_file" ]] || fail 'SwarmOps agent-token file must exist and be non-empty'
  [[ -s "$swarmops_registry_config_file" ]] || fail 'SwarmOps registry-config file must exist and be non-empty'
fi

if (( ${#releases[@]} )); then
  for release in "${releases[@]}"; do
    validate_release "$release"
  done
fi

printf '%s\n' '== Three-manager Swarm plan =='
printf 'manager-01: SSH %s@%s; Swarm %s\n' "$ssh_user" "$manager_01" "$advertise_01"
printf 'manager-02: SSH %s@%s; Swarm %s\n' "$ssh_user" "$manager_02" "$advertise_02"
printf 'manager-03: SSH %s@%s; Swarm %s\n' "$ssh_user" "$manager_03" "$advertise_03"
if [[ "$manager_01" == "$advertise_01" || "$manager_02" == "$advertise_02" || "$manager_03" == "$advertise_03" ]]; then
  printf '%s\n' 'Warning: an SSH address is also a Swarm address. Prefer private IPs and never expose Swarm ports publicly.' >&2
fi
if ((password_auth)); then
  printf '%s\n' 'Authentication: Ansible will prompt for the SSH password; the script never saves it.' >&2
fi
if ((ask_become_pass)); then
  printf '%s\n' 'Privilege escalation: Ansible will also prompt for the sudo password.' >&2
fi
if ((deploy_platform)); then
  printf 'Platform: deploy Traefik and SwarmOps at %s.\n' "$swarmops_host"
fi
if (( ${#releases[@]} )); then
  for release in "${releases[@]}"; do
    printf 'Release: %s with immutable tag %s.\n' "$release" "$tag"
  done
fi

if (( ! apply )); then
  printf '%s\n' 'Plan only: no local files, hosts, registry images, secrets, or stacks were changed. Re-run with --apply to execute.'
  exit 0
fi

write_inventory
write_host_file manager-01 "$manager_01"
write_host_file manager-02 "$manager_02"
write_host_file manager-03 "$manager_03"
printf '%s\n' 'Wrote ignored local inventory and Docker-context files.'

bootstrap_args=(--inventory "$inventory" --apply)
if ((password_auth)); then
  bootstrap_args+=(--password-auth)
fi
if ((ask_become_pass)); then
  bootstrap_args+=(--ask-become-pass)
fi
if ((install_password_helper)); then
  bootstrap_args+=(--install-password-helper)
fi
bash "$repo_root/scripts/bootstrap-swarm.sh" "${bootstrap_args[@]}"

for host in manager-01 manager-02 manager-03; do
  make -C "$repo_root" context HOST="$host"
done

if ((deploy_platform)) || (( ${#releases[@]} )); then
  make -C "$repo_root" clean-worktree
fi

if ((deploy_platform)); then
  make -C "$repo_root" secret-create HOST=manager-01 \
    SECRET=traefik_cf_dns_token_v1 FILE="$traefik_token_file"
  make -C "$repo_root" secret-create HOST=manager-01 \
    SECRET=traefik_dashboard_auth_v1 FILE="$traefik_dashboard_auth_file"
  make -C "$repo_root" secret-create HOST=manager-01 \
    SECRET=swarmops_admin_password_hash_v1 FILE="$swarmops_admin_password_hash_file"
  make -C "$repo_root" secret-create HOST=manager-01 \
    SECRET=swarmops_session_key_v1 FILE="$swarmops_session_key_file"
  make -C "$repo_root" secret-create HOST=manager-01 \
    SECRET=swarmops_agent_token_v1 FILE="$swarmops_agent_token_file"
  make -C "$repo_root" secret-create HOST=manager-01 \
    SECRET=swarmops_registry_config_v1 FILE="$swarmops_registry_config_file"
  make -C "$repo_root" stack-check STACK=traefik TAG="$tag"
  make -C "$repo_root" stack-check STACK=swarmops TAG="$tag"
  make -C "$repo_root" platform-deploy HOST=manager-01 TAG="$tag"
fi

if (( ${#releases[@]} )); then
  requires_swarmops_images=0
  for release in "${releases[@]}"; do
    [[ "$release" == swarmops ]] && requires_swarmops_images=1
  done
  if ((requires_swarmops_images)); then
    make -C "$repo_root" registry-login
    make -C "$repo_root" push TAG="$tag"
  fi
  for stack in "${releases[@]}"; do
    make -C "$repo_root" stack-check STACK="$stack" TAG="$tag"
    make -C "$repo_root" deploy STACK="$stack" HOST=manager-01 TAG="$tag"
  done
fi

printf '%s\n' 'Requested setup phases completed. Verify task placement, HTTPS, and critical product flows before a live domain cutover.'
